export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_ERROR = 'FETCH_SELLERS_ERROR';
export const FETCH_INVENTORY = 'FETCH_INVENTORY';

export const FETCH_SELLER_PRODUCTS = 'FETCH_SELLER_PRODUCTS';
export const FETCH_SELLER_PRODUCTS_SUCCESS = 'FETCH_SELLER_PRODUCTS_SUCCESS';
export const FETCH_SELLER_PRODUCTS_ERROR = 'FETCH_SELLER_PRODUCTS_ERROR';
export const SET_ACTIVE_PRODUCT = 'SET_ACTIVE_PRODUCT';

export const SET_SELLER_PRODUCTS_PAGE_NO = 'SET_SELLER_PRODUCTS_PAGE_NO';
export const SET_SELLER_PRODUCTS_PAGE_SIZE = 'SET_SELLER_PRODUCTS_PAGE_SIZE';
export const SET_SELLER_PRODUCTS_PAGE_COUNT = 'SET_SELLER_PRODUCTS_PAGE_COUNT';
export const SET_SELLER_PRODUCTS_COUNT = 'SET_SELLER_PRODUCTS_COUNT';
export const SET_SELLER_PRODUCTS_SINGLE_PAGE_ITEMS_COUNT =
  'SET_SELLER_PRODUCTS_SINGLE_PAGE_ITEMS_COUNT';

export const FETCH_PRODUCT_SELLERS = 'FETCH_PRODUCT_SELLERS';
export const FETCH_PRODUCT_SELLERS_SUCCESS = 'FETCH_PRODUCT_SELLERS_SUCCESS';
export const FETCH_PRODUCT_SELLERS_ERROR = 'FETCH_PRODUCT_SELLERS_ERROR';
export const SET_PRODUCT_SELLERS = 'SET_FETCH_SELLERS';

export const SEARCH_STATUS = {
  PENDING: 'pending',
  DONE: 'done',
};

export const selectItemsCountList = [
  {
    key: '25',
    text: '25',
    value: '25',
  },
  {
    key: '50',
    text: '50',
    value: '50',
  },
  {
    key: '100',
    text: '100',
    value: '100',
  },
];
