export const FETCH_SELLERS = 'FETCH_SELLERS';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';
export const FETCH_SELLERS_ERROR = 'FETCH_SELLERS_ERROR';
export const FETCH_INVENTORY = 'FETCH_INVENTORY';

export const FETCH_SELLER_PRODUCTS = 'FETCH_SELLER_PRODUCTS';
export const FETCH_SELLER_PRODUCTS_SUCCESS = 'FETCH_SELLER_PRODUCTS_SUCCESS';
export const FETCH_SELLER_PRODUCTS_ERROR = 'FETCH_SELLER_PRODUCTS_ERROR';

export const FETCH_PRODUCT_SELLERS = 'FETCH_PRODUCT_SELLERS';
export const FETCH_PRODUCT_SELLERS_SUCCESS = 'FETCH_PRODUCT_SELLERS_SUCCESS';
export const FETCH_PRODUCT_SELLERS_ERROR = 'FETCH_PRODUCT_SELLERS_ERROR';

export const SEARCH_STATUS = {
  PENDING: 'pending',
  DONE: 'done',
};
