import { Location } from '../../interfaces/SellerMap';

/* Actions */
export const actionTypes = {
  LOADING_SELLERS_FOR_MAP: 'LOADING_SELLERS_FOR_MAP',
  SET_SELLERS_FOR_MAP: 'SET_SELLERS_FOR_MAP',
  // Sellers details for cards
  LOADING_SELLER_DETAILS_FOR_MAP: 'LOADING_SELLER_DETAILS_FOR_MAP',
  SET_SELLER_DETAILS_FOR_MAP: 'SET_SELLER_DETAILS_FOR_MAP',
  SHOW_SELLER_DETAILS_CARD: 'SHOW_SELLER_DETAILS_CARD',
};

export const INITIAL_CENTER: Location = [37.09024, -95.712891];
export const INITIAL_ZOOM = 4.8;
export const MIN_ZOOM = 2.5;
export const MAX_ZOOM = 18;
export const WORLD_MAP_BOUNDS: Location[] = [
  [-90, -180],
  [90, 180],
];

export const DEFAULT_SELLER_INFO = {
  business_name: '',
  city: '',
  id: '',
  merchant_id: '',
  seller_link: '',
  seller_name: '',
  state: '',
  zip_code: '',
};

// Seller Limit Options
export const SELLER_LIMIT_OPTIONS = [
  {
    key: '1000',
    value: 1000,
    text: 'Top 1,000',
  },
  {
    key: '2000',
    value: 2000,
    text: 'Top 2,000',
  },
  {
    key: '5000',
    value: 5000,
    text: 'Top 5,000',
  },
  {
    key: '10000',
    value: 10000,
    text: 'Top 10,000',
  },
  {
    key: '20000',
    value: 20000,
    text: 'Top 20,000',
  },
  {
    key: '50000',
    value: 50000,
    text: 'Top 50,000',
  },
];

export const mapCountryKeyValuePair: { [key: string]: string } = {
  AE: 'United Arab Emirates',
  AL: 'Albania',
  AM: 'Armenia',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BO: 'Bolivia, Plurinational State of',
  BR: 'Brazil',
  BY: 'Belarus',
  CA: 'Canada',
  CH: 'Switzerland',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  FI: 'Finland',
  FR: 'France',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GG: 'Guernsey',
  GI: 'Gibraltar',
  GR: 'Greece',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IS: 'Iceland',
  IT: 'Italy',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KH: 'Cambodia',
  KR: 'Korea, Republic of',
  KZ: 'Kazakhstan',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MA: 'Morocco',
  MD: 'Moldova, Republic of',
  MK: 'Macedonia, the Former Yugoslav Republic of',
  MO: 'Macao',
  MT: 'Malta',
  MU: 'Mauritius',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NC: 'New Caledonia',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PR: 'Puerto Rico',
  PT: 'Portugal',
  PY: 'Paraguay',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russian Federation',
  SA: 'Saudi Arabia',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SV: 'El Salvador',
  SX: 'Sint Maarten (Dutch part)',
  TD: 'Chad',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TW: 'Taiwan, Province of China',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  VE: 'Venezuela, Bolivarian Republic of',
  VG: 'Virgin Islands, British',
  VI: 'Virgin Islands, U.S.',
  VN: 'Viet Nam',
  ZA: 'South Africa',
};

export const COUNTRY_DROPDOWN_LIST = Object.keys(mapCountryKeyValuePair).map(
  (countryKey: string) => {
    return {
      text: mapCountryKeyValuePair[countryKey],
      code: countryKey,
      value: countryKey,
      flag: countryKey.toLocaleLowerCase(),
      key: countryKey,
    };
  }
);
