export const SET_SUPPLIER_FILTER_UNIT_PROFIT = 'SET_SUPPLIER_FILTER_UNIT_PROFIT';
export const SET_SUPPLIER_FILTER_MARGIN = 'SET_SUPPLIER_FILTER_MARGIN';
export const SET_SUPPLIER_FILTER_UNITS_PER_MONTH = 'SET_SUPPLIER_FILTER_UNITS_PER_MONTH';
export const SET_SUPPLIER_FILTER_PROFIT_PER_MONTH = 'SET_SUPPLIER_FILTER_PROFIT_PER_MONTH';
