import React from 'react';
import { connect } from 'react-redux';
import { Modal } from 'semantic-ui-react';
import axios from 'axios';

/* Styling */
import styles from './index.module.scss';

/* Components */
import BoxHeader from '../../../../components/BoxHeader';
import BoxContainer from '../../../../components/BoxContainer';
import StartDateSelection from './StartDateSelection';
import LeadTimeSelection from './LeadTimeSelection';
import AutoGenerateDurationSelection from './AutoGenerateDurationSelection';
import OrderCreated from './OrderCreatedSuccess';

/* Interfaces */
import {
  CreateOrderPayload,
  PurchaseOrder,
} from '../../../../interfaces/PerfectStock/OrderPlanning';

/* Utils */
import { AppConfig } from '../../../../config';
import { sellerIDSelector } from '../../../../selectors/Seller';

/* Actions */
import {
  fetchInventoryTable,
  fetchPurchaseOrders,
  setActivePurchaseOrder,
} from '../../../../actions/PerfectStock/OrderPlanning';
import { error, success } from '../../../../utils/notifications';

/* Constants */
import { CREATE_ORDER_STATUS } from '../../../../constants/PerfectStock/OrderPlanning';

interface Props {
  open: boolean;
  onCloseModal: () => void;
  fetchPurchaseOrders: () => void;
  fetchInventoryTable: () => void;
  setActivePurchaseOrder: (order: PurchaseOrder) => void;
}

const CreateOrder = (props: Props) => {
  const {
    open,
    onCloseModal,
    fetchPurchaseOrders,
    fetchInventoryTable,
    setActivePurchaseOrder,
  } = props;

  const DEFAULT_ORDER: CreateOrderPayload = {
    date: '',
    lead_time_group_id: -1,
    approach: 'inventory',
    auto_generate_orders_days: -1,
  };

  const [createOrderPayload, setCreateOrderPayload] = React.useState<CreateOrderPayload>(
    DEFAULT_ORDER
  );
  const [createOrderStatus, setCreateOrderStatus] = React.useState<number>(
    CREATE_ORDER_STATUS.SELECT_START_DATE
  );

  const handleCreateOrder = async () => {
    try {
      const url = `${AppConfig.BASE_URL_API}sellers/${sellerIDSelector()}/purchase-order-templates`;
      const res = await axios.post(url, createOrderPayload);
      if (res.status === 201) {
        fetchPurchaseOrders();
        fetchInventoryTable();
        setActivePurchaseOrder(res.data);
        success('Successfully created smart order template.');
        setCreateOrderStatus(createOrderStatus + 1);
      } else {
        error('Failed to create new order.');
      }
    } catch (err) {
      console.error(err);
      error('Failed to add');
    }
  };

  /* Reset the create order flow every time user cancels/opens modal*/
  React.useEffect(() => {
    setCreateOrderPayload(DEFAULT_ORDER);
    setCreateOrderStatus(CREATE_ORDER_STATUS.SELECT_START_DATE);
  }, [open]);

  let content: JSX.Element;
  let headerContent: string;
  switch (createOrderStatus) {
    case CREATE_ORDER_STATUS.SELECT_START_DATE:
      content = (
        <StartDateSelection
          onCloseModal={onCloseModal}
          createOrderPayload={createOrderPayload}
          setCreateOrderPayload={setCreateOrderPayload}
          handleNext={() => setCreateOrderStatus(createOrderStatus + 1)}
        />
      );
      headerContent = '1ST ORDER DATE';
      break;
    case CREATE_ORDER_STATUS.SELECT_LEAD_TIME:
      content = (
        <LeadTimeSelection
          handlePrevious={() => setCreateOrderStatus(createOrderStatus - 1)}
          createOrderPayload={createOrderPayload}
          setCreateOrderPayload={setCreateOrderPayload}
          handleNext={() => setCreateOrderStatus(createOrderStatus + 1)}
        />
      );
      headerContent = 'LEAD TIME';
      break;

    case CREATE_ORDER_STATUS.SELECT_AUTO_GENERATE_DURATION:
      content = (
        <AutoGenerateDurationSelection
          handlePrevious={() => setCreateOrderStatus(createOrderStatus - 1)}
          createOrderPayload={createOrderPayload}
          setCreateOrderPayload={setCreateOrderPayload}
          handleCreateOrder={handleCreateOrder}
        />
      );
      headerContent = 'SMART PURCHASE ORDER';
      break;

    case CREATE_ORDER_STATUS.ORDER_CREATION_SUCCESS:
      content = <OrderCreated handleNext={() => setCreateOrderStatus(createOrderStatus + 1)} />;
      headerContent = 'SMART ORDER TEMPLATE';
      break;

    default:
      content = <div>Error</div>;
      headerContent = 'Error';
  }

  return (
    <Modal open={open} className={styles.modalWrapper} onClose={onCloseModal}>
      <div>
        <BoxHeader>{headerContent}</BoxHeader>
        <BoxContainer className={styles.createOrderContent}>{content}</BoxContainer>
      </div>
    </Modal>
  );
};

const mapStateToProps = () => ({});

const mapDispatchToProps = (dispatch: any) => {
  return {
    fetchPurchaseOrders: () => {
      dispatch(fetchPurchaseOrders());
    },
    fetchInventoryTable: () => {
      dispatch(fetchInventoryTable());
    },
    setActivePurchaseOrder: (order: PurchaseOrder) => {
      dispatch(setActivePurchaseOrder(order));
    },
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(CreateOrder);
