export const tempOrgData = [
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Vikki',
    last_name: 'Anderson',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [],
    teaser: {
      emails: [
        {
          email: 'fir**********************',
          type: 'professional',
        },
      ],
      phones: [],
    },
    title: 'Controller',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '1999 - 2000 Master of Science in Accounting @ University of North Carolina at Greensboro',
      '1996 - 1999 Bachelor of Science in Accounting @ University of North Carolina at Greensboro',
    ],
    jobs: [
      'Controller @ Firefly Store Solutions',
      'Controller @ Transcription Relief Services',
      'Accounting Manager @ Forman Rossabi Black Pa',
    ],
    id: '63afb17c427b5af8a08a1237',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: true,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Pamela',
    last_name: 'Hodges',
    links: {
      linkedin: null,
    },
    location: 'High Point, North Carolina, United States',
    skills: [],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Purchasing and Sourcing Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: [
      'Purchasing and Sourcing Manager @ Firefly Store Solutions',
      'Buyer Research and Development @ Haeco Americas',
      'Procurement Officer and Procurement Administrator @ State of West Virginia',
    ],
    id: '63afb17c427b5af8a08a1238',
    is_looked_up: false,

    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Emily',
    last_name: 'Moore',
    links: {
      twitter: null,
      googleplus: null,
      facebook: null,
      linkedin: null,
      pinterest: null,
    },
    location: 'Peachtree City, GA, US',
    skills: [
      'Logistics',
      'Management',
      'Microsoft Office',
      'Sourcing',
      'Project Management',
      'Product Development',
      'Operations Management',
      'Team Building',
      'Supply Chain Management',
      'Negotiation',
      'Supply Chain',
      'Purchasing',
      'Inventory Control',
      'ERP',
      'Strategic Sourcing',
      'Strategic Planning',
      'Project Planning',
      'Pricing',
      'Procurement',
      'Global Sourcing',
    ],
    teaser: {
      emails: [
        {
          email: 'fir**********************',
          type: 'professional',
        },
        {
          email: 'gma******',
          type: 'personal',
        },
      ],
      phones: [
        {
          number: '336-451*****',
        },
      ],
    },
    title: 'Purchasing and Planning Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '2001 - 2006 Bachelor Of Science in Kinesiology, Exercise Science @ University of North Carolina at Greensboro',
    ],
    jobs: [
      'Purchasing and Planning Manager @ Firefly Store Solutions',
      'Director of Global Sourcing @ Firefly Store Solutions',
    ],
    id: '63afb17c427b5af8a08a1239',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Gerald',
    last_name: 'Horne',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [
      'Leadership',
      'Microsoft Excel',
      'Inventory Management',
      'Supply Management',
      'Negotiation',
      'Strategic Planning',
      'Purchasing',
      'Operations Management',
      'Logistics Management',
      'Warehousing',
      'Operations',
      'Logistics',
    ],
    teaser: {
      emails: [
        {
          email: 'rob**********',
          type: 'professional',
        },
      ],
      phones: [
        {
          number: '33684*****',
        },
      ],
    },
    title: 'Purchasing and Operations Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Purchasing and Operations Manager @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a123a',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'David',
    last_name: 'González',
    links: {
      twitter: null,
      facebook: null,
      linkedin: null,
      myspace: null,
      'instagram.com': null,
    },
    location: 'Raleigh, North Carolina, United States',
    skills: [
      'Budgets',
      'Business Planning',
      'Business Strategy',
      'Cross-functional Team Leadership',
      'Customer Service',
      'Forecasting',
      'Inventory Management',
      'Leadership',
      'Logistics',
      'Management',
      'Marketing Strategy',
      'Microsoft Excel',
      'Microsoft Office',
      'Negotiation',
      'Operations Management',
      'Process Improvement',
      'SAP',
      'Supply Chain',
      'Team Building',
      'Purchasing',
      'Strategic Planning',
      'Cross Functional Team Leadership',
      'Supply Chain Management',
      'Procurement',
      'Logistics Management',
    ],
    teaser: {
      emails: [
        {
          email: 'yah******',
          type: 'personal',
        },
      ],
      phones: [
        {
          number: '787-316*****',
        },
        {
          number: '787-384*****',
        },
        {
          number: '787-321*****',
        },
        {
          number: '787-384*****',
        },
        {
          number: '210-238*****',
        },
        {
          number: '939-350*****',
        },
      ],
    },
    title: 'Usa North East Purchasing Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '1996 - 2000 Bachelor of Business Administration (B.B.A.) in  Accounting @ intermerican University',
      '1994 - 1996 Computer Programming in  Programación de computadoras @ IBC',
    ],
    jobs: [
      'Usa North East Purchasing Manager @ Firefly Store Solutions',
      'Usa North East and Spain Buyer and Planner @ Goya Foods',
      'Purchasing and Logistics Manager @ Ashley Furniture Industries',
    ],
    id: '63afb17c427b5af8a08a123b',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Lisa',
    last_name: 'Newman',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [
      'Accounts Payable',
      'Accounts Receivable',
      'Invoicing',
      'General Ledger',
      'Collections',
    ],
    teaser: {
      emails: [
        {
          email: 'fir**********************',
          type: 'professional',
        },
      ],
      phones: [
        {
          number: '33673*****',
        },
      ],
    },
    title: 'Accounts Payable',
    marketplace_id: 'ATVPDKIKX0DER',
    education: ['1980 - 1984 Southeast Guilford High School'],
    jobs: [
      'Accounts Payable @ Firefly Store Solutions',
      'Accounts Receivable Clerk @ Vanguard Celluar At&t',
    ],
    id: '63afb17c427b5af8a08a123c',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Timothy',
    last_name: 'Clay',
    links: {
      linkedin: null,
    },
    location: 'Climax, North Carolina, United States',
    skills: [
      'Forklift Operation',
      'Warehousing',
      'Forklift Operator',
      'Pallet Jack',
      'Order Picking',
    ],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Warehouse Worker',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Warehouse Worker @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a123d',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Kim',
    last_name: 'Nelson',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [
      'Management',
      'Leadership',
      'Microsoft Excel',
      'Customer Service',
      'Supply Chain',
      'Microsoft Office',
    ],
    teaser: {
      emails: [
        {
          email: 'rob**********',
          type: 'professional',
        },
      ],
      phones: [],
    },
    title: 'Logistics',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Logistics @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a123e',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Angela',
    last_name: 'York',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [
      'Retail',
      'Customer Service',
      'Merchandising',
      'Sales',
      'Team Leadership',
      'Operations Management',
      '15+ yrs Customer Service',
      'Accounts Re',
      'Team Building',
      'Store Management',
      'Visual Merchandising',
      'Quality',
      'Computer',
      'Credit',
      'Merchandis',
      'Servant',
      'Excel',
      'Machine Knitting',
      'Returns',
      'Problem Solving',
      'Collections',
      'Negotiation',
      'Customer Satisfaction',
      'Inventory Control',
      'Logistics',
      'Sales Management',
      'Inventory Management',
      'Microsoft Excel',
      'Leadership',
      'Strategic Planning',
      'Microsoft Word',
      'Management',
      'Project Management',
      'Credit Analysis',
    ],
    teaser: {
      emails: [
        {
          email: 'rob**********',
          type: 'professional',
        },
      ],
      phones: [
        {
          number: '33673*****',
        },
      ],
    },
    title: 'Credit and Returns Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Credit and Returns Manager @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a123f',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Joe',
    last_name: 'Zalewski',
    links: {
      linkedin: null,
    },
    location: 'Oak Forest, Illinois, United States',
    skills: [
      'Microsoft Word',
      'Sales',
      'Microsoft Excel',
      'Shipping',
      'Training',
      'International Shipping',
      'Warehouse Management',
      'Supply Chain Management',
      'Customs Regulations',
    ],
    teaser: {
      emails: [],
      phones: [
        {
          number: '70853*****',
        },
      ],
    },
    title: 'Shipping Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Shipping Manager @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1240',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Nicholas',
    last_name: 'Malone',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [
      'Inventory Management',
      'Warehouse Management',
      'Outlook',
      'Microsoft Office',
      'Microsoft Excel',
      'Leadership',
      'Training',
      'Microsoft Word',
      'PowerPoint',
      'Access',
      'Sourcing',
      'Team Building',
      'Operations Management',
    ],
    teaser: {
      emails: [],
      phones: [
        {
          number: '27634*****',
        },
      ],
    },
    title: 'Warehouse Staff',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '2000 - 2004 Bachelor of Science @ North Carolina Agricultural and Technical State University',
    ],
    jobs: ['Warehouse Staff @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1241',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Lisa',
    last_name: 'Kiser',
    links: {
      linkedin: null,
    },
    location: 'Wilmington, North Carolina, United States',
    skills: [],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Sales at Firefly Store Solutions',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Sales at Firefly Store Solutions @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1242',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Kierra',
    last_name: 'Campbell',
    links: {
      linkedin: null,
      facebook: null,
    },
    location: 'Chapel Hill, North Carolina, United States',
    skills: [
      'Leadership',
      'International Political Economy',
      'Spanish Translation',
      'Social Media',
      'Social Justice',
      'PowerPoint',
      'International',
      'Public Speaking',
      'Youth Leadership',
      'English to Spanish',
      'Data Entry',
      'Spanish Teaching',
      'Microsoft PowerPoint',
      'Event Planning',
      'Social Sciences',
      'Data Analysis',
      'Political Science',
      'Communication',
      'International Relations',
      'International Development',
      'Data Coding',
      'Facebook',
      'Nonprofit Organizations',
      'Microsoft Office',
      'Microsoft Word',
      'Microsoft Excel',
      'Social Networking',
      'Time Management',
      'Community Outreach',
      'Editing',
      'Customer Service',
      'International Political',
      'Teamwork',
      'Research',
      'Spanish',
    ],
    teaser: {
      emails: [
        {
          email: 'yah******',
          type: 'personal',
        },
        {
          email: 'mar*********************',
          type: 'professional',
        },
      ],
      phones: [
        {
          number: '33669*****',
        },
      ],
    },
    title: 'Executive Director',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '2012 - 2016 Bachelor Of Arts in Political Science, Global Studies @ University of North Carolina at Chapel Hill',
      '2014 - 2014 Chinese University Of Hong Kong',
      'University of North Carolina at Chapel Hill',
    ],
    jobs: [
      'Executive Director @ Firefly Store Solutions',
      'Customer Service Representative @ Firefly Store Solutions',
      'Executive Assistant @ Midatlantic Roofing Systems',
    ],
    id: '63afb17c427b5af8a08a1243',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Vikki',
    last_name: 'Taylor',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, NC, US',
    skills: [],
    teaser: {
      emails: [
        {
          email: 'gma******',
          type: 'personal',
        },
        {
          email: 'ton********',
          type: 'professional',
        },
        {
          email: 'trs*************',
          type: 'professional',
        },
        {
          email: 'tri*********',
          type: 'professional',
        },
      ],
      phones: [
        {
          number: '336-210*****',
        },
        {
          number: '336-218*****',
        },
        {
          number: '336-299*****',
        },
        {
          number: '336-358*****',
        },
        {
          number: '336-855*****',
        },
        {
          number: '336-274*****',
        },
      ],
    },
    title: '',
    marketplace_id: 'ATVPDKIKX0DER',
    education: ['University of North Carolina at Greensboro'],
    jobs: [],
    id: '63afb17c427b5af8a08a1244',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Michael',
    last_name: 'Macmahon',
    links: {
      linkedin: null,
      facebook: null,
    },
    location: 'Seattle, Washington, United States',
    skills: [],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Warehouse Management',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Warehouse Management @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1245',
    is_looked_up: false,
    is_decision_maker: true,
    is_head: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Joe',
    last_name: 'Zalewski',
    links: {
      linkedin: null,
    },
    location: 'Oak Forest, Illinois, United States',
    skills: [
      'Warehousing',
      'Shipping',
      'Warehouse Management',
      'Distribution Center Operations',
      'Logistics',
      'Inventory Control',
      'Forklift Operator',
      'Inventory Management',
      'Logistics Management',
      'Transportation',
      'Operations Management',
      'Purchasing',
      'Materials Management',
      'Transportation Management',
      'Freight',
      'Continuous Improvement',
      'Customer Service',
    ],
    teaser: {
      emails: [
        {
          email: 'fir**********************',
          type: 'professional',
        },
      ],
      phones: [],
    },
    title: 'Shipping and Receiving Manager',
    marketplace_id: 'ATVPDKIKX0DER',
    education: ['Oak Forest High School'],
    jobs: ['Shipping and Receiving Manager @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1246',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Bhargi',
    last_name: 'Patel',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Account Specialist',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [
      '2004 - 2008 Bachelors in Accounting, Finance @ North Carolina Agricultural and Technical State University',
    ],
    jobs: ['Account Specialist @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1247',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Danice',
    last_name: 'Hughes',
    links: {
      linkedin: null,
    },
    location: 'Greensboro, North Carolina, United States',
    skills: [],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Customer Service Representative',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Customer Service Representative @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1248',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Angela',
    last_name: 'Walter',
    links: {
      linkedin: null,
    },
    location: 'High Point, North Carolina, United States',
    skills: [
      'Customer Service',
      'Customer Satisfaction',
      'Time Management',
      'Teamwork',
      'Team Leadership',
      'Data Entry',
      'Outlook',
    ],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Customer Service',
    marketplace_id: 'ATVPDKIKX0DER',
    education: ['Hillside High school. Hillside NJ'],
    jobs: ['Customer Service @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a1249',
    is_looked_up: false,
  },
  {
    seller_id: 'A0902783Y8LJQ6UO9JS4',
    company: 'Firefly Store Solutions',
    first_name: 'Joe',
    last_name: 'Reyes',
    links: {
      linkedin: null,
    },
    location: 'Grand Prairie, Texas, United States',
    skills: [
      'Logistics',
      'Merchandising',
      'Management',
      'Warehousing',
      'Cycle Counting',
      'Purchasing',
      'Inventory Accuracy',
      'Forklift Operator',
      'Inventory Control',
      'Distribution Center Operations',
      'Pallet Jack',
      'Order Picking',
      'Supply Chain Operations',
      'Warehouse Control',
      'Recieving',
      'Inventory Analysis',
      'UPS Shipping',
      'Inventory',
      'Stock Control',
      'Vendor Managed Inventory',
      'Physical Inventory',
    ],
    teaser: {
      emails: [],
      phones: [],
    },
    title: 'Warehouse',
    marketplace_id: 'ATVPDKIKX0DER',
    education: [],
    jobs: ['Warehouse @ Firefly Store Solutions'],
    id: '63afb17c427b5af8a08a124a',
    is_looked_up: false,
  },
];
