/* Actions types for keywords reverse */

export const actionTypes = {
  /* Action for keyword request */
  IS_FETCHING_KEYWORD_REVERSE_REQUEST_ID: 'IS_FETCHING_KEYWORD_REVERSE_REQUEST_ID',
  SET_KEYWORD_REVERSE_REQUEST_ID: 'SET_KEYWORD_REVERSE_REQUEST_ID',

  /* Actions for the main table */
  IS_LOADING_KEYWORD_REVERSE_TABLE: 'IS_LOADING_KEYWORD_REVERSE_TABLE',
  SET_KEYWORD_REVERSE_TABLE_RESULTS: 'SET_KEYWORD_REVERSE_TABLE_RESULTS',
  SET_KEYWORD_REVERSE_TABLE_PAGINATION_INFO: 'SET_KEYWORD_REVERSE_TABLE_PAGINATION_INFO',
};
