import { Column } from '../../interfaces/Container/settings';

export const CONTAINERS_SETTINGS_COLUMNS: Column[] = [
  {
    width: 50,
    dataKey: 'isRowSelected',
    title: '',
    isRadio: true,
    type: 'text',
    align: 'right',
  },
  {
    width: 120,
    dataKey: 'name',
    title: 'Type',
    type: 'text',
    align: 'left',
  },
  {
    width: 120,
    dataKey: 'container_size_cbm',
    title: 'Volume (CBM)',
    type: 'number',
    align: 'center',
  },
  {
    width: 160,
    dataKey: 'max_size_perc',
    title: 'Order efficiency (%)',
    type: 'number',
    isEditable: true,
    align: 'center',
  },
  {
    width: 120,
    dataKey: 'max_order_cbm',
    title: 'Max order (CBM)',
    type: 'number',
    align: 'center',
  },
  {
    width: 35,
    dataKey: 'isMarketPriceSelected',
    title: '',
    isRadio: true,
    type: 'text',
    align: 'right',
  },
  {
    width: 180,
    dataKey: 'market_price',
    title: 'Latest market price ($ USD)',
    type: 'number',
    isRadio: false,
    prepend: '$',
    align: 'left',
  },
  {
    width: 35,
    dataKey: 'isCustomPriceSelected',
    title: '',
    isRadio: true,
    type: 'text',
    align: 'right',
  },
  {
    width: 180,
    dataKey: 'price',
    title: 'Custom price ($ USD)',
    type: 'number',
    isEditable: true,
    isRadio: false,
    prepend: '$',
    align: 'left',
  },
];
