export const FETCH_SELLER_DATABASE = 'FETCH_SELLER_DATABASE';
export const FETCH_SELLER_DATABASE_SUCCESS = 'FETCH_SELLER_DATABASE_SUCCESS';
export const FETCH_SELLER_DATABASE_ERROR = 'FETCH_SELLER_DATABASE_ERROR';
export const LOADING_DATABASE = 'LOADING_DATABASE';

export const SET_SELLER_DATABASE_PAGE_NO = 'SET_SELLER_DATABASE_PAGE_NO';
export const SET_SELLER_DATABASE_PAGE_SIZE = 'SET_SELLER_DATABASE_PAGE_SIZE';
export const SET_SELLER_DATABASE_PAGE_COUNT = 'SET_SELLER_DATABASE_PAGE_COUNT';
export const SET_SELLER_DATABASE_COUNT = 'SET_SELLER_DATABASE_COUNT';
export const SET_SELLER_DATABASE_SINGLE_PAGE_ITEMS_COUNT =
  'SET_SELLER_DATABASE_SINGLE_PAGE_ITEMS_COUNT';

export const SET_SELLER_DATABASE_SORT = 'SET_SELLER_DATABASE_SORT';
export const SET_SELLER_DATABASE_SORT_DIRECTION = 'SET_SELLER_DATABASE_SORT_DIRECTION';
