export const SET_IS_INCOMING_NOTIFICATION = 'SET_IS_INCOMING_NOTIFICATION';
export const SET_NOTIFICATIONS_LIST = 'SET_NOTIFICATIONS_LIST';
export const SET_IS_LOADING_NOTIFICATIONS = 'SET_IS_LOADING_NOTIFICATIONS';
