/* All action types */
export const actionTypes = {
  SET_LEAD_TIME_JOB_PROJECTION_ID: 'SET_LEAD_TIME_JOB_PROJECTION_ID',
  SET_IS_FETCHING_PROGRESS_FOR_LEAD_TIME_JOB: 'SET_IS_FETCHING_PROGRESS_FOR_LEAD_TIME_JOB',
  SET_REFRESH_PROGRESS: 'SET_REFRESH_PROGRESS',
};
