export const FOO = 'BAR';
/* All action types */
export const actionTypes = {
  IS_LOADING_SALES_PROJECTION_RESULTS: 'IS_LOADING_SALES_PROJECTION_RESULTS',
  SET_SALES_PROJECTION_RESULTS: 'SET_SALES_PROJECTION_RESULTS',
};
