/* All action types */
export const actionTypes = {
  SET_TEAM_LEAD_JOB_PROJECTION_ID: 'SET_TEAM_LEAD_JOB_PROJECTION_ID',
  SET_IS_FETCHING_PROGRESS_FOR_TEAM_LEAD_JOB: 'SET_IS_FETCHING_PROGRESS_FOR_TEAM_LEAD_JOB',
  SET_REFRESH_PROGRESS: 'SET_REFRESH_PROGRESS',
};
