/* All action types */
export const actionTypes = {
  IS_LOADING_SALES_PROJECTION_RESULTS: 'IS_LOADING_SALES_PROJECTION_RESULTS',
  SET_SALES_PROJECTION_RESULTS: 'SET_SALES_PROJECTION_RESULTS',
  SET_SALES_PROJECTION_UPDATE_DATE: 'SET_SALES_PROJECTION_UPDATE_DATE',
  SET_REFRESH_SALES_PROJECTION_ID: 'SET_REFRESH_SALES_PROJECTION_ID',
  SET_IS_FETCHING_PROGRESS_FOR_REFRESH: 'SET_IS_FETCHING_PROGRESS_FOR_REFRESH',
  SET_REFRESH_PROGRESS: 'SET_REFRESH_PROGRESS',
};
